#+title: Описание
#+author: Whatis
#+date: <2024-12-27 Пт 14:04>
#+tags: :dobro:

* Установка
  1. Установите [[https://nodejs.org/][Node JS]]
  2. Сделайте клон репозиторий и запустите =npm install= в корневой директории

* Использование
** Основное
   - В =redocly.yaml=, в опции =apis= указан список доступных "разделов" которые можно запустить/собрать ([name]).
   - Все шаблоны и вложения находятся в директории docs
   - Все openapi конфиги находятся в директории openapi

** =start.sh [--api=apiName] [-p|--port=port] [-c|--config=openapiConfig] ...=
   Создает venv для split, устанавливает requirements.txt в окружение,
   декомпозирует большой openapi.yaml, запускает предпросмотр документации
   по переданному apiName или первый попавшийся по переданному port или по
   порту 8080

** =npm start [?name]=
   Запускает предпросмотр документации

** =npm run build [?name]=
   Делает сборку документации

** =npm test=
   Валидирует конфиги

** =split.sh [openapi.yaml] [outDir]=
   Подбробнее об аргументах можно посмотреть:
   =split.sh -h=.

   Разбирает большой openapi yaml на составные
   части. На текущий момент разделяет только по
   тегам:

   1. Ищет все пути, обрабатывает ссылки

      Выносит все внутренние ссылки ($ref) в
      поддиректорию refs ({outDir}/refs).

      Заменяет соответственно пути ссылок из внутренних
      на внешние (=#/components/schema/asd= станет =refs/somehash.yaml=
      или =somehash.yaml=)

   2. Собирает и группирует полученные из 1го пункта пути по тегам.
   3. Генерирует разделенные по тегам данные.

      По-сути если есть тэг Address, то в файле Address.yaml
      будет не полноценный конфиг openapi, а список путей
